id: run_python_server
learningObjectives:
hints:
  - Follow the instructions in the README to set up and run the server.
  - Test the API endpoints to verify the server's functionality.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Hey, it's Lucca here. So, Ness wants us to migrate our Python server into
              Node.js. Why? She says Node.js is faster, more scalable, and
              better suited for our evolving needs, not sure I completly agree but ok...
          - text: First, grab the project and run the existing Python server to make sure
              it's working as expected. We need to understand the current setup
              before diving into changes.
          - text: Try to get all tasks (via the `/tasks` endpoint`) to verify everything works fine, and let me know what's the second task in the list.
trigger:
  type: user_message
  params:
    person: lucca
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: "/Create a time machine from a cardboard box/i"
      then:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
              - text: "Oh right, I remember that one! I'll mark this step as complete."
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
              - text: "Are you sure? This is not what I remember. Try again."
        
