id: create_node_server_prompt
learningObjectives:
  - Create a basic Node.js server using GitHub Copilot.
hints:
  - Ensure GitHub Copilot is enabled in your editor.
  - Use the '@workspace /new' command to prompt Copilot to start a new Node.js
    server template.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Alright, the Python server is working. Now, let's use a bit of Copilot
              magic.
          - text: "Open GitHub Copilot and use the '@workspace /new' option to create a new
              project. We want a simple Node.js server with Express. Here's an
              example prompt you can use: 'Create a new Node.js Express
              server'."
          - text: Once the project is generated, you might need to go back to the original
              project using File > Open Folder. Feel free to create the project
              multiple times until it looks good. Don't forget to add a
              Dockerfile!
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
