id: create_node_server_prompt
learningObjectives:
  - Create a new project using GitHub Copilot chat.
hints:
  - Ensure GitHub Copilot is enabled in your editor.
  - Use the '@workspace /new' command to prompt Copilot to start a new Node.js server template.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Alright, the Python server is working. Now, let's use a bit of Copilot magic.
          - text: "Open GitHub Copilot chat and use the '@workspace /new' option to create a new project and put it under a `node-server` folder. We want a simple Node.js server with Docker. Here's an example prompt you can use:"
          - text: |
              ```
              @workspace /new Scaffold code for a simple JS express server that has no endpoints.
              The server should listen on port 8001, and use nodemon so everychange in the code will reflect in `yarn start`.
              With the server please include a simple Docker file to run it
              ```
          - text: "![](${copilotchatworkspace.png})"
          - text: After running the prompt, make sure to click the "Create Workspace" button to finalize the creation of the new workspace.
          - text: Once the project is generated, you might need to go back to the original project using File > Open Folder. Feel free to create the project multiple times until it looks good.
          - text: |
              The Docker file should look like this:
              ```
              FROM node:14

              WORKDIR /app

              COPY package*.json /app
              RUN yarn install
              EXPOSE 8001

              CMD [ "yarn", "start" ]
              ```
          - text: "Your workspace should look something like this:"
          - text: "![](${file-structure.png})"
          - text: Let me know when you managed to create the node files.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
