id: run_both_servers
learningObjectives:
  - Run both servers
hints:
  - Update the docker-compose.yml to include the Node.js service.
  - Set the correct ports for the Node.js server.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Next, let's make sure both servers can run together.
          - text:
              We need to edit the docker-compose file to run the Python server and the new Node
              server (Node on port 8001). This should allow us to see if everything is working in harmony.
          - text: "We can use GitHub Copilot to help us with this task too:"
          - text: |
              ```
              @workspace modify the commands to run both servers, the Python app (on port 8000) and the Node app (on port 8001) in the #file:docker-compose.yml 
              ```
          - text: If all is well, :instruction[create a new branch and open a PR with your changes, and I'll review it.] This was once a nightmare without Copilot, but look at us now!

githubActions:
  commands:
    - cmd: docker compose up -d
    - cmd: sleep 5
    - cmd: curl localhost:8001
    - cmd: curl localhost:8000

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: lucca
                message: "On it, I'll review the changes right away."
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: "Nailed it! Excellent job! You can now merge the PR."
            - actionId: github_pr_approve
              params:
                person: lucca
                message: "Nailed it! Excellent job! You can now merge the PR."
        github_pr_workflow_complete_failure:
          do:
            - actionId: github_pr_reject
              params:
                person: lucca
                message: "Weird, I tried to run the servers using `docker compose up` but couldn't find anything on port 8000 or 8001. Are you sure it's working for you?"
        github_pr_merged:
          do:
            - actionId: finish_step
