id: run_both_servers
learningObjectives:
  - Run both servers
hints:
  - Update the docker-compose.yml to include the Node.js service.
  - Set the correct ports for the Node.js server.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Next, let's make sure both servers can run together.
          - text: Edit the docker-compose file to run the Python server and the new Node
              server (Node on port 3001). This should allow us to see if
              everything is working in harmony.
          - text: "Here's a snippet you can use to add the Node.js service to the `docker-compose.yml` file:"
          - text: |
              ```
              node-server:
                build:
                  context: ./node-server
                  dockerfile: Dockerfile
                ports:
                  - 8001:8001
                volumes:
                  - ./node-server/src:/app/src
              ```
          - text: If all is well, create a PR with these changes. This was once a nightmare
              without Copilot, but look at us now!

githubActions:
  commands:
    - cmd: docker compose up -d
    - cmd: sleep 5
    - cmd: curl localhost:8001
    - cmd: curl localhost:8000

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: github_pr_comment
            params:
              person: lucca
              message: "On it, I'll review the changes right away."
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
              - text: "Nailed it! Excellent job! You can now merge the PR."
          - actionId: github_pr_approve
            params:
              person: lucca
              message: "Nailed it! Excellent job! You can now merge the PR."
        github_pr_workflow_complete_failure:
          do:
          - actionId: github_pr_reject
            params:
              person: lucca
              message: "Weird, I tried to run the servers using `docker compose up` but couldn't find anything on port 8000 or 8001, are you sure it's working for you?"
        github_pr_merged:
          do:
          - actionId: finish_step
