id: migrate_endpoints
learningObjectives:
  - Migrate node code using GitHub Copilot.
  - Adding context to GitHub Copilot chat.
hints:
  - Understand the logic of the `/get_tasks` and `/add_task` routes in Python before migrating.
  - Copy the Python code and ask Copilot to translate it to Node.js.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Sweet, we've got our Node server. Now, let's put Copilot to even better use.
          - text: Use GitHub Copilot to migrate the endpoints from the Python server to our Node server.
          - text: We can do it easily by giving copilot the code we want to migrate and ask them for help.
          - text: Add the Python code you want to migrate [to the chat](https://code.visualstudio.com/docs/copilot/getting-started-chat#_add-chat-context) and ask Copilot to translate it to Node.js.
          - text: Once the migration is complete, commit the changes and open a PR. Ness will be thrilled with our progress.

githubActions:
  commands:
    - cmd: docker compose up -d
    - cmd: sleep 5
    - cmd: |
        curl -X POST -H "Content-Type: application/json" -d "{\"text\": \"New task\"}" http://localhost:8001/tasks
    - cmd: |
        curl localhost:8001/tasks | grep "New task"

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: github_pr_comment
            params:
              person: lucca
              message: "Got it! Let me review the changes and get back to you."
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
              - text: "Good job, you can now merge the PR."
          - actionId: github_pr_approve
            params:
              person: lucca
              message: "Good job, you can now merge the PR."
        github_pr_workflow_complete_failure:
          do:
          - actionId: github_pr_reject
            params:
              person: lucca
              message: "I'm sorry, but I can't approve this PR, I found some issues when testing the endpoints."
