id: 04_migrate_get_tasks
learningObjectives:
  - Migrate the '/get_tasks' route to the Node.js server.
hints:
  - Understand the logic of the '/get_tasks' route in Python before migrating.
  - Use GitHub Copilot to convert the Python code to Node.js.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Sweet, we've got our Node server. Now, let's put Copilot to even better
              use.
          - text: Use GitHub Copilot to migrate the '/get_tasks' route from the Python
              server to our Node server.
          - text: Go to the Python route, copy the code, and ask Copilot to translate it to
              Node.js. Commit the code and open a PR once you're done.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
