id: update_readme
learningObjectives:
  - Update the README file to include new Node.js server details.
  - Using inline chat.
hints:
  - Use GitHub Copilot's inline chat to update the README.
  - Ensure the README accurately reflects the changes made.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: We're almost there. Just one last task before we wrap up.
          - text: Let's update the README file to reflect our new Node.js server and the
              migration details. Thankfully, Copilot can help with this too.
          - text: Select the text in the README and use [inline
              chat](https://code.visualstudio.com/docs/copilot/getting-started-chat#_stay-in-the-flow-with-inline-chat)
              to ask Copilot for updates. Once you're done, commit the changes
              and open a final PR. Ness will likely throw a party with all this progress.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: Congratulations, you've successfully migrated the Python server to Node
                using GitHub Copilot! We've upgraded our tech stack and now have
                a Node server handling our tasks. Ness is going to be thrilled.
                Great job!
      - actionId: finish_step
